/**
 * The eight steps, as a stream of events.
 *
 * Yields one complete object at a time - never a partially-parsed tree. A half
 * object cannot be rendered and cannot be validated, and the build timeline
 * exists to show real progress, not a spinner with a label on it.
 *
 * Every detail line is computed from what actually happened. "Parsed 247 tags",
 * not "Thinking...". That register is the product.
 *
 * Phase 4 of docs/BUILD_PLAN.md.
 */

import {
  alarmLamp,
  alarmSummary,
  lamp,
  numericDisplay,
  rectangle,
  screenOf,
  textBox,
} from "@/lib/ote/parts";
import { DARK_GREY, GREEN, WHITE } from "@/lib/ote/palette";
import type { Wire } from "@/lib/ote/bindings";
import type { Alarm, Part, Variable } from "@/lib/ote/schema";
import { validateProject } from "@/lib/validation/rules";
import type { GenerationEvent, PipelineStep } from "@/types/events";
import { inferEquipment, proposeAlarms, type InferredEquipment } from "./infer";
import {
  activeProvider,
  hasApiKey,
  planScreen,
  type Provider,
  type ScreenPlan,
} from "./plan";

const SCREEN = { width: 1024, height: 600 };

const now = () => new Date().toLocaleTimeString("en-GB", { hour12: false });

const log = (message: string): GenerationEvent => ({ type: "log", at: now(), message });

const step = (
  s: PipelineStep,
  state: "running" | "done" | "failed",
  detail?: string,
): GenerationEvent => ({ type: "step", step: s, state, detail });

export interface PipelineInput {
  intent: string;
  variables: Variable[];
}

/** A screen laid out from equipment, plus what drives each object. */
function layout(
  plan: ScreenPlan,
  equipment: InferredEquipment[],
): { parts: Part[]; wires: Wire[]; viewId: string } {
  const parts: Part[] = [];
  const wires: Wire[] = [];
  const place = (part: Part, tag?: string) => {
    parts.push(part);
    if (tag) wires.push({ part, tag, property: "CurrentValue" });
    return part;
  };

  place(rectangle("Banner", { left: 0, top: 0, width: SCREEN.width, height: 56 }, { fill: GREEN, border: GREEN }));
  place(textBox("Title", plan.title, { left: 20, top: 14, width: 520, height: 30 }, { size: 20, colour: WHITE, bold: true }));
  place(textBox("Subtitle", "Generated by HMI Copilot", { left: 700, top: 20, width: 300, height: 24 }, { size: 11, colour: WHITE }));

  const chosen = plan.include
    .map((id) => equipment.find((e) => e.id === id))
    .filter((e): e is InferredEquipment => Boolean(e));

  const wantsStatus = plan.sections.includes("status");
  const wantsProcess = plan.sections.includes("process");

  // Status panel: one lamp per running state, one per fault.
  if (wantsStatus) {
    place(rectangle("Panel_Status", { left: 20, top: 76, width: 480, height: 224 }));
    place(textBox("Lbl_Status", "STATUS", { left: 36, top: 88, width: 200, height: 22 }, { size: 12, colour: DARK_GREY }));

    let column = 0;
    for (const unit of chosen) {
      const run = unit.roles.find((r) => r.role === "running");
      const fault = unit.roles.find((r) => r.role === "fault");
      if (!run && !fault) continue;
      if (column > 1) break; // two fit; the rest belong on a second screen

      const x = 40 + column * 230;
      const key = unit.id.replace(/[^A-Za-z0-9]/g, "");
      if (run) {
        place(
          lamp(`Lamp_${key}_RUN`, `${unit.label}\nSTOPPED`, `${unit.label}\nRUNNING`,
            { left: x, top: 120, width: 200, height: 76 }),
          run.tag,
        );
      }
      if (fault) {
        place(
          alarmLamp(`Lamp_${key}_FLT`, "OK", "FAULT", { left: x, top: 208, width: 200, height: 60 }),
          fault.tag,
        );
      }
      column += 1;
    }
  }

  // Process panel: one numeric per measured value.
  if (wantsProcess) {
    const left = wantsStatus ? 520 : 20;
    const width = wantsStatus ? 484 : 984;
    place(rectangle("Panel_Process", { left, top: 76, width, height: 224 }));
    place(textBox("Lbl_Process", "PROCESS", { left: left + 16, top: 88, width: 200, height: 22 }, { size: 12, colour: DARK_GREY }));

    const readings = chosen
      .flatMap((unit) =>
        unit.roles
          .filter((r) => r.dataType !== "BOOL" && r.dataType !== "STRING")
          .map((r) => ({ unit, role: r })),
      )
      .slice(0, 2);

    readings.forEach(({ role }, i) => {
      const y = 124 + i * 84;
      const name = role.role[0].toUpperCase() + role.role.slice(1);
      const key = role.tag.replace(/[^A-Za-z0-9]/g, "");
      place(textBox(`Lbl_${key}`, name, { left: left + 20, top: y + 14, width: 120, height: 28 }, { size: 14 }));
      place(numericDisplay(`Num_${key}`, { left: left + 150, top: y, width: 200, height: 60 }), role.tag);
      const unit = /percent|%/i.test(role.comment) ? "%" : /lpm|flow/i.test(role.comment) ? "LPM" : "";
      if (unit) {
        place(textBox(`Unit_${key}`, unit, { left: left + 364, top: y + 14, width: 100, height: 28 }, { size: 14, colour: DARK_GREY }));
      }
    });
  }

  if (plan.wantsAlarmBanner) {
    place(textBox("Lbl_Alarms", "ACTIVE ALARMS", { left: 20, top: 316, width: 300, height: 24 }, { size: 12, colour: DARK_GREY }));
    place(alarmSummary("AlarmBanner", { left: 20, top: 344, width: 984, height: 236 }));
  }

  const screen = screenOf(plan.screenName, parts, SCREEN);
  return { parts, wires, viewId: screen.Children[0].UniqueId };
}

/** A plan good enough to build from when no key is configured. */
function fallbackPlan(intent: string, equipment: InferredEquipment[]): ScreenPlan {
  const hasReadings = equipment.some((e) =>
    e.roles.some((r) => r.dataType !== "BOOL" && r.dataType !== "STRING"),
  );
  const hasFaults = equipment.some((e) => e.roles.some((r) => r.role === "fault"));
  const first = equipment[0];
  const name =
    first && first.kind !== "instrument"
      ? `${first.kind[0].toUpperCase()}${first.kind.slice(1)}Station1`
      : "Overview";

  return {
    title: intent.trim().slice(0, 60) || "Overview",
    screenName: name.replace(/[^A-Za-z0-9_]/g, ""),
    include: equipment.map((e) => e.id),
    sections: hasReadings ? ["status", "process"] : ["status"],
    wantsAlarmBanner: hasFaults || hasReadings,
    rationale: `Laid out ${equipment.length} unit${equipment.length === 1 ? "" : "s"} from the tag names.`,
  };
}

export async function* runPipeline(
  input: PipelineInput,
): AsyncGenerator<GenerationEvent> {
  const { intent, variables } = input;

  // --- 1 ingest -----------------------------------------------------------
  yield step("ingest", "running");
  if (variables.length === 0) {
    yield step("ingest", "failed", "no tags supplied");
    yield { type: "error", message: "No tags to generate from. Import a PLC tag export first." };
    return;
  }
  yield { type: "tags", variables };
  yield step("ingest", "done", `${variables.length} tags`);
  yield log(`Parsed ${variables.length} tags`);

  // --- 2 infer ------------------------------------------------------------
  yield step("infer", "running");
  const equipment = inferEquipment(variables);
  const kinds = new Map<string, number>();
  for (const unit of equipment) kinds.set(unit.kind, (kinds.get(unit.kind) ?? 0) + 1);
  const summary = [...kinds.entries()].map(([k, n]) => `${n} ${k}${n === 1 ? "" : "s"}`).join(", ");
  yield { type: "equipment", equipment };
  yield step("infer", "done", summary);
  yield log(`Detected ${summary} from the tag names`);

  // --- 3 select -----------------------------------------------------------
  yield step("select", "running");
  let plan: ScreenPlan | null = null;
  let provider: Provider | null = null;
  const configured = hasApiKey();
  const waitingOn = activeProvider();
  if (configured) {
    // The model call is the only slow step - seconds, against milliseconds for
    // everything else. Saying which provider is being asked keeps that gap
    // legible instead of looking like a stall. It states what is happening, not
    // what anything is thinking.
    yield log(`Asking ${waitingOn === "gemini" ? "Gemini" : "Claude"} to read the request`);
    try {
      const planned = await planScreen(intent, equipment);
      if (planned) {
        plan = planned.plan;
        provider = planned.provider;
      }
    } catch (error) {
      // A model failure must not take the screen down. Say so and carry on.
      yield log(
        `Model unavailable (${error instanceof Error ? error.message : "unknown"}); laying out from the tag names`,
      );
    }
  }
  plan ??= fallbackPlan(intent, equipment);

  const PROVIDER_NAME: Record<Provider, string> = {
    gemini: "Gemini",
    claude: "Claude",
  };

  yield log(
    provider
      ? `${PROVIDER_NAME[provider]} read the request: ${plan.rationale}`
      : configured
        ? `Laid out from the tag names: ${plan.rationale}`
        : `No model key set — laid out from the tag names: ${plan.rationale}`,
  );
  yield step("select", "done", `${plan.include.length} of ${equipment.length} units`);

  // --- 4 layout -----------------------------------------------------------
  yield step("layout", "running");
  const { parts, wires, viewId } = layout(plan, equipment);
  for (const part of parts) {
    yield { type: "object", part, parentId: viewId };
  }
  yield step("layout", "done", `${parts.length} objects`);
  yield log(`Placed ${parts.length} objects on ${plan.screenName}`);

  // --- 5 alarms -----------------------------------------------------------
  yield step("alarms", "running");
  const alarms: Alarm[] = plan.wantsAlarmBanner
    ? proposeAlarms(equipment).map((p) => ({
        Message: p.message,
        Trigger: p.trigger,
        AlarmType: p.level,
        AlarmRecordType: p.kind === "bit" ? 1 : 2,
        Severity: p.severity,
        Value: p.value,
      }))
    : [];
  for (const alarm of alarms) yield { type: "alarm", alarm };
  yield step("alarms", "done", `${alarms.length} configured`);
  if (alarms.length > 0) {
    const bit = alarms.filter((a) => a.AlarmRecordType === 1).length;
    yield log(`Configured ${alarms.length} alarms (${bit} bit, ${alarms.length - bit} level)`);
  }

  // --- 6 bindings ---------------------------------------------------------
  yield step("bindings", "running");
  for (const wire of wires) {
    yield {
      type: "binding",
      tag: wire.tag,
      target: wire.part.Name,
      property: wire.property,
    };
  }
  const total = wires.length + alarms.length;
  yield step("bindings", "done", `${total} of ${total} bound`);
  yield log(`Bound ${wires.length} display properties and ${alarms.length} alarm triggers`);

  // --- 7 validate ---------------------------------------------------------
  yield step("validate", "running");
  const screen = screenOf(plan.screenName, parts, SCREEN);
  const project = {
    name: plan.screenName,
    target: { model: "HMIST6500AWADI", width: SCREEN.width, height: SCREEN.height },
    screens: [screen],
    variables,
    alarms,
    wires,
  };
  const findings = validateProject(project);
  for (const finding of findings) {
    yield {
      type: "finding",
      severity: finding.severity,
      message: finding.message,
      objectId: finding.objectId,
      suggestion: finding.suggestion,
    };
  }
  const errors = findings.filter((f) => f.severity === "error").length;
  const warnings = findings.filter((f) => f.severity === "warning").length;
  yield step("validate", errors > 0 ? "failed" : "done", `${errors} errors, ${warnings} warnings`);

  // --- 8 package ----------------------------------------------------------
  yield step("package", "running");
  yield step("package", "done", "ready to export");
  yield log(`${plan.screenName} ready — ${parts.length} objects, ${total} bindings`);

  yield { type: "done", screenId: screen.UniqueId };
}
