"use client";

/**
 * The left pane: one column, top to bottom - you describe what you need, and
 * the run's output arrives underneath it.
 *
 * Tag import and engineering standards used to live here too, stacked below the
 * prompt. They have their own routes on the nav rail, and stacking three
 * unrelated sections in a scrolling column is what let them overlap: each was a
 * `min-h-0` flex child, so instead of scrolling they compressed into each other.
 * The prompt keeps this pane; the rest went where it already belonged.
 *
 * Reference screens 1, 3, 5, 6. Phases 3 and 4 of docs/BUILD_PLAN.md.
 */

import { useState } from "react";
import { Loader, Sparkles } from "lucide-react";
import { useProject } from "@/store/project";
import { useGeneration } from "@/components/generation/useGeneration";
import { RunOutput } from "@/components/generation/RunOutput";
import { Badge, Button, Textarea } from "@/components/ui";

const MAX_INTENT = 500;

/** Reference screen 5 shows these six, two to a row. */
const QUICK = [
  "Pump station",
  "Motor control",
  "Add alarms",
  "Create trend",
  "Use template",
  "Follow standards",
];

const PLACEHOLDER =
  "Create a pump station screen with 2 pumps. Show running status, start/stop buttons, flow, pressure, temperature and a high-level alarm. Use our company style.";

export function IntentPanel() {
  const [intent, setIntent] = useState("");
  const { generate, source, error } = useGeneration();
  const generating = useProject((s) => s.generating);

  const ready = intent.trim().length > 0;

  return (
    <aside className="flex h-full w-full min-h-0 flex-col">
      {/* The question. Fixed height so the answer below gets the rest. */}
      <div className="shrink-0 space-y-3 p-3">
        <h2 className="text-sm font-semibold text-text-primary">
          Describe what you need
        </h2>

        <Textarea
          value={intent}
          onChange={(e) => setIntent(e.target.value)}
          maxLength={MAX_INTENT}
          showCount
          rows={5}
          disabled={generating}
          aria-label="Describe what you need"
          placeholder={PLACEHOLDER}
          className="pb-7"
        />

        <div className="flex flex-wrap gap-1.5">
          {QUICK.map((q) => (
            <button
              key={q}
              type="button"
              disabled={generating}
              onClick={() => setIntent(q)}
              className="focus-ring rounded-full border border-line px-2.5 py-1 text-xs text-text-secondary transition hover:border-brand-500 hover:text-brand-400 disabled:opacity-40"
            >
              {q}
            </button>
          ))}
        </div>

        <Button
          variant="primary"
          size="lg"
          block
          disabled={!ready || generating}
          onClick={() => void generate(intent.trim() || PLACEHOLDER)}
          icon={
            generating ? (
              <Loader size={16} className="animate-spin" />
            ) : (
              <Sparkles size={16} />
            )
          }
        >
          {generating ? "Generating…" : "Generate Screen"}
        </Button>

        {error && <p className="text-xs text-status-alarm">{error}</p>}

        {source && !generating && !error && (
          <p className="flex items-center gap-2 text-xs text-text-muted">
            <Badge tone={source === "api" ? "ok" : "warn"}>
              {source === "api" ? "/api/generate" : "local pipeline"}
            </Badge>
            {source === "api" ? "generated by the model" : "the route did not answer"}
          </p>
        )}
      </div>

      {/* The answer. Takes whatever height is left, and scrolls on its own. */}
      <div className="flex min-h-0 flex-1 flex-col border-t border-line-subtle">
        <h3 className="shrink-0 px-3 pb-2 pt-3 text-xs font-semibold uppercase tracking-wide text-text-muted">
          Output
        </h3>
        <RunOutput />
      </div>
    </aside>
  );
}
