"use client";

/**
 * The left pane: describe what you need, import tags, pick standards.
 * Reference screens 1, 3, 5, 6. Phases 3 and 4 of docs/BUILD_PLAN.md.
 *
 * Generate runs the pipeline in useGeneration, which asks /api/generate first
 * and falls back to the local emitter while that route is still the Phase 4
 * stub. Which one ran is stated rather than hidden - a demo that cannot tell
 * you whether the model was involved is not worth much.
 */

import { useState } from "react";
import { Loader, ShieldCheck, Sparkles } from "lucide-react";
import { useProject } from "@/store/project";
import { useGeneration } from "@/components/generation/useGeneration";
import { TagImport, TagSummary } from "@/components/tags";
import { Badge, Button, Panel, Textarea } from "@/components/ui";

const MAX_INTENT = 500;

/** Reference screen 5 shows these six, two to a row. */
const QUICK = [
  "Pump station",
  "Motor control",
  "Add alarms",
  "Create trend",
  "Use template",
  "Follow standards",
];

const PLACEHOLDER =
  "Create a pump station screen with 2 pumps. Show running status, start/stop buttons, flow, pressure, temperature and a high-level alarm. Use our company style.";

export function IntentPanel() {
  const [intent, setIntent] = useState("");
  const { generate, source, error } = useGeneration();
  const generating = useProject((s) => s.generating);
  const variables = useProject((s) => s.variables);

  const ready = intent.trim().length > 0;

  return (
    <aside className="flex h-full w-full flex-col overflow-y-auto">
      <Panel title="1. Describe what you need" collapsible>
        <div className="space-y-3">
          <Textarea
            value={intent}
            onChange={(e) => setIntent(e.target.value)}
            maxLength={MAX_INTENT}
            showCount
            rows={5}
            disabled={generating}
            aria-label="Describe what you need"
            placeholder={PLACEHOLDER}
            className="pb-7"
          />

          <div>
            <p className="mb-1.5 text-xs font-medium text-text-muted">Quick prompts</p>
            <div className="flex flex-wrap gap-1.5">
              {QUICK.map((q) => (
                <button
                  key={q}
                  type="button"
                  disabled={generating}
                  onClick={() => setIntent(q)}
                  className="focus-ring rounded-full border border-line px-2.5 py-1 text-xs text-text-secondary transition hover:border-brand-500 hover:text-brand-400 disabled:opacity-40"
                >
                  {q}
                </button>
              ))}
            </div>
          </div>

          <Button
            variant="primary"
            size="lg"
            block
            disabled={!ready || generating}
            onClick={() => void generate(intent.trim() || PLACEHOLDER)}
            icon={
              generating ? (
                <Loader size={16} className="animate-spin" />
              ) : (
                <Sparkles size={16} />
              )
            }
          >
            {generating ? "Generating…" : "Generate Screen"}
          </Button>

          {error && <p className="text-xs text-status-alarm">{error}</p>}

          {source && !generating && !error && (
            <p className="flex items-center gap-2 text-xs text-text-muted">
              <Badge tone={source === "api" ? "ok" : "warn"}>
                {source === "api" ? "/api/generate" : "local pipeline"}
              </Badge>
              {source === "api"
                ? "generated by the model"
                : "the route is still the Phase 4 stub"}
            </p>
          )}
        </div>
      </Panel>

      <Panel
        title="2. Import PLC tags"
        collapsible
        actions={
          variables.length > 0 && (
            <span className="text-xs tabular-nums text-text-muted">
              {variables.length.toLocaleString()}
            </span>
          )
        }
      >
        <TagImport compact />
      </Panel>

      {variables.length > 0 && <TagSummary className="px-3 pb-3" />}

      <Panel title="3. Engineering standards" collapsible>
        <button
          type="button"
          className="focus-ring flex w-full items-center gap-3 rounded-md border border-line p-3 text-left transition hover:border-line-strong"
        >
          <ShieldCheck size={18} aria-hidden className="shrink-0 text-status-info" />
          <span className="min-w-0">
            <span className="block truncate text-sm font-medium">
              Schneider Standard
            </span>
            <span className="block truncate text-xs text-text-muted">
              Colours, fonts, layout, naming
            </span>
          </span>
        </button>
      </Panel>
    </aside>
  );
}
