/**
 * The Phase 1 gate.
 *
 * Nothing downstream is worth building until this passes: the TypeScript
 * packager must produce a project with the same structure as the proven Python
 * one, and the resulting file must open in EcoStruxure Operator Terminal Expert.
 *
 * The backslash assertion is the important one. Python's zipfile silently
 * rewrites entry names to forward slashes; if jszip does anything similar, the
 * product will refuse the archive. Assert against the raw bytes, never against
 * the library's own name list, which may normalise on read.
 */

import { describe, expect, it } from "vitest";

describe.skip("packager (Phase 1)", () => {
  it("writes ZIP entry names with backslash separators", async () => {
    // const bytes = await packageProject(fixture);
    // const text = Buffer.from(bytes).toString("latin1");
    // expect(text).toContain("Screens\\");
    // expect(text).not.toContain("Screens/");
  });

  it("writes Variables.db with one row per tag", async () => {});

  it("writes Alarm.db with bit and level alarms", async () => {});

  it("emits a Bindings.dat graph joining Sources to Targets", async () => {});

  it("matches the reference project generated by tools/make_project.py", async () => {});
});
