/**
 * The Phase 1 gate.
 *
 * Nothing downstream is worth building until this passes: the TypeScript
 * packager must produce a project structurally identical to the proven Python
 * one, and the resulting file must open in EcoStruxure Operator Terminal Expert.
 *
 * This suite proves the structure. Opening the file is a manual step - see
 * `npm run build:demo`, which writes demo_project/HMICopilot_TS.eote.
 *
 * The backslash assertions are the important ones. Python's zipfile silently
 * rewrites entry names to forward slashes; if jszip does anything similar the
 * product will refuse the archive. Assert against the raw bytes, never against
 * the library's own name list, which may normalise on read.
 */

import fs from "node:fs";
import path from "node:path";
import JSZip from "jszip";
import initSqlJs from "sql.js";
import { beforeAll, describe, expect, it } from "vitest";

import { buildDemoProject } from "@/lib/ote/demo-project";
import { packageProject } from "@/lib/ote/packager";
import { loadSkeleton } from "@/lib/ote/skeleton";
import { Screen } from "@/lib/ote/schema";

const REFERENCE = path.join(
  __dirname,
  "..",
  "..",
  "demo_project",
  "HMICopilot_PumpStation.eote",
);

const hasSkeleton = fs.existsSync(
  path.join(__dirname, "..", "skeleton", "manifest.json"),
);

/** Named so the failure explains itself rather than looking like a broken test. */
const gate = hasSkeleton
  ? describe
  : describe.skip.bind(describe) as unknown as typeof describe;

if (!hasSkeleton) {
  console.warn(
    "\n  Skipping the packager gate: no skeleton/.\n" +
      "  Run `npm run setup:skeleton` on a machine with EcoStruxure installed.\n",
  );
}

let bytes: Uint8Array;
let entryNames: string[];
let rawText: string;

gate("packager (Phase 1)", () => {
  beforeAll(async () => {
    bytes = await packageProject(buildDemoProject(), await loadSkeleton());
    rawText = Buffer.from(bytes).toString("latin1");
    const zip = await JSZip.loadAsync(bytes);
    entryNames = Object.keys(zip.files).filter((n) => !zip.files[n].dir);
  }, 60_000);

  it("writes nested entry names with backslash separators", () => {
    expect(rawText).toContain("Screens\\");
    expect(rawText).not.toContain("Screens/");
  });

  it("carries every entry the skeleton supplied", async () => {
    const skeleton = await loadSkeleton();
    for (const name of skeleton.entries.keys()) {
      expect(entryNames).toContain(name);
    }
  });

  it("adds the screen, its metadata and its local variables", () => {
    const screens = entryNames.filter((n) => n.startsWith("Screens\\"));
    expect(screens).toContain("Screens\\Hierarchy.dat");
    expect(screens.filter((n) => n.endsWith("Screen.dat"))).toHaveLength(1);
    expect(screens.filter((n) => n.endsWith("Metadata.dat"))).toHaveLength(1);
    expect(screens.filter((n) => n.endsWith("LocalVariables.db"))).toHaveLength(1);
  });

  it("produces a screen that parses through the schema", async () => {
    const zip = await JSZip.loadAsync(bytes);
    const name = entryNames.find((n) => n.endsWith("Screen.dat"))!;
    const screen = Screen.parse(JSON.parse(await zip.file(name)!.async("string")));
    expect(screen.Name).toBe("PumpStation1");
    expect(screen.Children[0].Children).toHaveLength(19);
  });

  it("matches the reference project generated by tools/make_project.py", async () => {
    const reference = await JSZip.loadAsync(fs.readFileSync(REFERENCE));
    const refNames = Object.keys(reference.files).filter((n) => !reference.files[n].dir);

    // GUIDs differ every run, so compare the shape rather than the names.
    const shape = (names: string[]) =>
      names
        .map((n) => n.replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi, "<guid>"))
        .sort();

    expect(shape(entryNames)).toEqual(shape(refNames));

    const ours = await JSZip.loadAsync(bytes);
    const refScreenName = refNames.find((n) => n.endsWith("Screen.dat"))!;
    const ourScreenName = entryNames.find((n) => n.endsWith("Screen.dat"))!;

    const refScreen = JSON.parse(await reference.file(refScreenName)!.async("string"));
    const ourScreen = JSON.parse(await ours.file(ourScreenName)!.async("string"));

    // Same objects, same order, same geometry - only the ids differ.
    const strip = (node: Record<string, unknown>): unknown => {
      const { UniqueId, ...rest } = node;
      void UniqueId;
      const children = rest.Children as Record<string, unknown>[] | undefined;
      return children
        ? { ...rest, Children: children.map(strip) }
        : rest;
    };

    expect(strip(ourScreen)).toEqual(strip(refScreen));
  });

  it("writes the tags into Variables.db", async () => {
    const zip = await JSZip.loadAsync(bytes);
    const SQL = await initSqlJs({
      locateFile: (f) => path.join(path.dirname(require.resolve("sql.js")), f),
    });
    const db = new SQL.Database(await zip.file("Variables.db")!.async("uint8array"));
    const [result] = db.exec('SELECT "Name","DataType","Comments" FROM Variables ORDER BY "Order"');
    db.close();

    expect(result.values).toHaveLength(7);
    expect(result.values[0]).toEqual(["PMP_101_RUN", "BOOL", "Pump 1 running"]);
    expect(result.values[6]).toEqual(["LT_101_HI", "BOOL", "Tank high level"]);
  });

  it("writes bit and level alarms into Alarm.db", async () => {
    const zip = await JSZip.loadAsync(bytes);
    const SQL = await initSqlJs({
      locateFile: (f) => path.join(path.dirname(require.resolve("sql.js")), f),
    });
    const db = new SQL.Database(await zip.file("Alarm.db")!.async("uint8array"));
    // "Value" holds the setpoint and is a SQL keyword - unquoted it silently
    // resolves to the string "Value" instead of the column.
    const [alarms] = db.exec(
      'SELECT "Message","AlarmType","AlarmRecordType","Severity","Value" FROM Alarm ORDER BY "Order"',
    );
    const [groups] = db.exec('SELECT "Name" FROM AlarmGroup');
    db.close();

    expect(groups.values).toEqual([["AlarmGroup1"]]);
    expect(alarms.values).toHaveLength(5);
    expect(alarms.values[0]).toEqual(["Pump 1 fault", 1, 1, 5, "0"]);
    expect(alarms.values[3]).toEqual(["Tank level high", 2, 2, 3, "85"]);
    expect(alarms.values[4]).toEqual(["Tank level critically high", 1, 2, 5, "95"]);
  });

  it("emits a binding graph joining every tag to what it drives", async () => {
    const zip = await JSZip.loadAsync(bytes);
    const graph = JSON.parse(await zip.file("Bindings.dat")!.async("string"));

    expect(graph.Sources).toHaveLength(7);
    expect(graph.Targets).toHaveLength(11);
    expect(graph.Bindings).toHaveLength(11);

    const display = graph.Bindings.filter(
      (b: { TargetProperty: string }) => b.TargetProperty === "CurrentValue",
    );
    const alarms = graph.Bindings.filter(
      (b: { TargetProperty: string }) => b.TargetProperty === "VariableName",
    );
    expect(display).toHaveLength(6);
    expect(alarms).toHaveLength(5);

    // A display binding carries the .Value suffix; an alarm binding does not.
    expect(display[0].BindingText).toMatch(/\.Value$/);
    expect(display[0].Mode).toBe(2);
    expect(alarms[0].BindingText).not.toMatch(/\.Value$/);
    expect(alarms[0].Mode).toBe(1);

    // Every binding resolves to a real source and a real target.
    for (const b of graph.Bindings) {
      expect(graph.Sources[Number(b.Sources)]).toBeDefined();
      expect(graph.Targets[b.Target]).toBeDefined();
      expect(graph.Targets[b.Target].ReferenceId).toBe(b.Target);
    }

    // LT_101_PV drives the level display plus two alarms - the case that is a
    // commissioning bug when it is wired by hand.
    const level = graph.Sources.find(
      (s: { ObjectFullName: string }) => s.ObjectFullName === "LT_101_PV",
    );
    const driven = graph.Bindings.filter(
      (b: { Sources: string }) => Number(b.Sources) === level.ReferenceId,
    );
    expect(driven).toHaveLength(3);
  });

  it("refuses to bind a tag that is not declared", async () => {
    const project = buildDemoProject();
    project.wires[0].tag = "NOT_A_TAG";
    await expect(packageProject(project, await loadSkeleton())).rejects.toThrow(
      /NOT_A_TAG/,
    );
  });
});
