/**
 * The pump station, composed with the part factories.
 *
 * This is the same project tools/make_project.py produces, expressed in
 * TypeScript - which makes it the thing the Phase 1 test compares against. Once
 * the generation pipeline lands (Phase 4) the model produces this shape instead
 * of it being written by hand, but the shape does not change.
 */

import {
  alarmLamp,
  alarmSummary,
  lamp,
  numericDisplay,
  rectangle,
  screenOf,
  textBox,
} from "./parts";
import { DARK_GREY, GREEN, WHITE } from "./palette";
import type { Wire } from "./bindings";
import type { Alarm, Part, Variable } from "./schema";
import type { PackageInput } from "./packager";

export const SCREEN = { width: 1024, height: 600 };

export const DEMO_VARIABLES: Variable[] = [
  { Name: "PMP_101_RUN", DataType: "BOOL", Comments: "Pump 1 running", DeviceAddress: "" },
  { Name: "PMP_101_FLT", DataType: "BOOL", Comments: "Pump 1 fault", DeviceAddress: "" },
  { Name: "PMP_102_RUN", DataType: "BOOL", Comments: "Pump 2 running", DeviceAddress: "" },
  { Name: "PMP_102_FLT", DataType: "BOOL", Comments: "Pump 2 fault", DeviceAddress: "" },
  { Name: "FT_101_PV", DataType: "REAL", Comments: "Flow, LPM", DeviceAddress: "" },
  { Name: "LT_101_PV", DataType: "REAL", Comments: "Tank level, percent", DeviceAddress: "" },
  { Name: "LT_101_HI", DataType: "BOOL", Comments: "Tank high level", DeviceAddress: "" },
];

/**
 * A bit alarm fires on a BOOL going true; a level alarm fires when a numeric
 * crosses a threshold. AlarmType 1=HiHi 2=Hi 3=Lo 4=LoLo, AlarmRecordType
 * 1=bit 2=level - both read off the shipped Alarm sample.
 */
export const DEMO_ALARMS: Alarm[] = [
  { Message: "Pump 1 fault", Trigger: "PMP_101_FLT", AlarmType: 1, AlarmRecordType: 1, Severity: 5, Value: "0" },
  { Message: "Pump 2 fault", Trigger: "PMP_102_FLT", AlarmType: 1, AlarmRecordType: 1, Severity: 5, Value: "0" },
  { Message: "Tank high level", Trigger: "LT_101_HI", AlarmType: 1, AlarmRecordType: 1, Severity: 3, Value: "0" },
  { Message: "Tank level high", Trigger: "LT_101_PV", AlarmType: 2, AlarmRecordType: 2, Severity: 3, Value: "85" },
  { Message: "Tank level critically high", Trigger: "LT_101_PV", AlarmType: 1, AlarmRecordType: 2, Severity: 5, Value: "95" },
];

export function buildDemoProject(name = "PumpStation1"): PackageInput {
  const parts: Part[] = [];
  const wires: Wire[] = [];

  const place = (part: Part, tag?: string, property = "CurrentValue") => {
    parts.push(part);
    if (tag) wires.push({ part, tag, property });
    return part;
  };

  // --- banner -------------------------------------------------------------
  place(rectangle("Banner", { left: 0, top: 0, width: SCREEN.width, height: 56 }, { fill: GREEN, border: GREEN }));
  place(textBox("Title", "Pump Station 1", { left: 20, top: 14, width: 420, height: 30 }, { size: 20, colour: WHITE, bold: true }));
  place(textBox("Subtitle", "Generated by HMI Copilot", { left: 700, top: 20, width: 300, height: 24 }, { size: 11, colour: WHITE }));

  // --- pumps --------------------------------------------------------------
  place(rectangle("Panel_Pumps", { left: 20, top: 76, width: 480, height: 224 }));
  place(textBox("Lbl_Pumps", "PUMPS", { left: 36, top: 88, width: 200, height: 22 }, { size: 12, colour: DARK_GREY }));

  const pumps = [
    { label: "PUMP 1", key: "PUMP1", run: "PMP_101_RUN", fault: "PMP_101_FLT" },
    { label: "PUMP 2", key: "PUMP2", run: "PMP_102_RUN", fault: "PMP_102_FLT" },
  ];

  pumps.forEach((pump, i) => {
    const x = 40 + i * 230;
    place(
      lamp(`Lamp_${pump.key}_RUN`, `${pump.label}\nSTOPPED`, `${pump.label}\nRUNNING`,
        { left: x, top: 120, width: 200, height: 76 }),
      pump.run,
    );
    place(
      alarmLamp(`Lamp_${pump.key}_FLT`, "OK", "FAULT",
        { left: x, top: 208, width: 200, height: 60 }),
      pump.fault,
    );
  });

  // --- process values -----------------------------------------------------
  place(rectangle("Panel_Process", { left: 520, top: 76, width: 484, height: 224 }));
  place(textBox("Lbl_Process", "PROCESS", { left: 536, top: 88, width: 200, height: 22 }, { size: 12, colour: DARK_GREY }));

  const values = [
    { label: "Flow", unit: "LPM", tag: "FT_101_PV" },
    { label: "Level", unit: "%", tag: "LT_101_PV" },
  ];

  values.forEach((value, i) => {
    const y = 124 + i * 84;
    place(textBox(`Lbl_${value.label}`, value.label, { left: 540, top: y + 14, width: 120, height: 28 }, { size: 14 }));
    place(numericDisplay(`Num_${value.label}`, { left: 670, top: y, width: 200, height: 60 }), value.tag);
    place(textBox(`Unit_${value.label}`, value.unit, { left: 884, top: y + 14, width: 100, height: 28 }, { size: 14, colour: DARK_GREY }));
  });

  // --- alarms -------------------------------------------------------------
  place(textBox("Lbl_Alarms", "ACTIVE ALARMS", { left: 20, top: 316, width: 300, height: 24 }, { size: 12, colour: DARK_GREY }));
  place(alarmSummary("AlarmBanner", { left: 20, top: 344, width: 984, height: 236 }));

  return {
    name,
    // Matches the skeleton's Target.dat: "1024 x 600" on an HMIST6500AWADI.
    // The packager refuses a project whose declared panel differs from the file.
    target: { model: "HMIST6500AWADI", width: SCREEN.width, height: SCREEN.height },
    screens: [screenOf(name, parts, SCREEN)],
    variables: DEMO_VARIABLES,
    alarms: DEMO_ALARMS,
    wires,
  };
}
